export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const FETCH_CAKES_START = "FETCH_CAKES_START";
export const FETCH_CAKES = "FETCH_CAKES";
export const FETCH_CAKES_FAILED = "FETCH_CAKES_FAILED";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_EMAIL = "AUTH_EMAIL";
export const AUTH_START = "AUTH_START";

export const SAVE_ORDER_START = "SAVE_ORDER_START";
export const SAVE_ORDER = "SAVE_ORDER";
export const SAVE_ORDER_FAILED = "SAVE_ORDER_FAILED";

export const FETCH_MY_ORDERS_START = "FETCH_MY_ORDERS_START";
export const FETCH_MY_ORDERS = "FETCH_MY_ORDERS";
export const FETCH_MY_ORDERS_FAILED = "FETCH_MY_ORDERS_FAILED";

export const REMOVING_PRODUCT = "REMOVING_PRODUCT";
export const NOT_REMOVING_PRODUCT = "NOT_REMOVING_PRODUCT";
